/**
  *  This file is part of Carma (Retroduction.org).
  *
  *  Carma is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
  *  the Free Software Foundation, either version 3 of the License, or
  *  (at your option) any later version.
  *
  *  Carma is distributed in the hope that it will be useful,
  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  *  GNU General Public License for more details.
  *
  *  You should have received a copy of the GNU General Public License
  *  along with Carma.  If not, see <http://www.gnu.org/licenses/>.
  *
  * Copyright Retroduction.org (c) 2007-2010
  */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.12 at 08:28:31 PM CEST 
//


package com.retroduction.carma.xmlreport.om;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.retroduction.carma.xmlreport.om package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.retroduction.carma.xmlreport.om
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassUnderTest }
     * 
     */
    public ClassUnderTest createClassUnderTest() {
        return new ClassUnderTest();
    }

    /**
     * Create an instance of {@link Mutant }
     * 
     */
    public Mutant createMutant() {
        return new Mutant();
    }

    /**
     * Create an instance of {@link MutationRun }
     * 
     */
    public MutationRun createMutationRun() {
        return new MutationRun();
    }

    /**
     * Create an instance of {@link MutationRatio }
     * 
     */
    public MutationRatio createMutationRatio() {
        return new MutationRatio();
    }

    /**
     * Create an instance of {@link ProcessingInfo }
     * 
     */
    public ProcessingInfo createProcessingInfo() {
        return new ProcessingInfo();
    }

}
