//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.05 at 10:03:07 PM CEST 
//


package com.retroduction.carma.xmlreport.om;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassUnderTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassUnderTest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="packageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processingInfo" type="{}ProcessingInfo"/>
 *         &lt;element name="mutationRatio" type="{}MutationRatio"/>
 *         &lt;element name="baseClassFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseSourceFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mutant" type="{}Mutant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="executedTests" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassUnderTest", propOrder = {
    "className",
    "packageName",
    "processingInfo",
    "mutationRatio",
    "baseClassFile",
    "baseSourceFile",
    "mutant",
    "executedTests"
})
public class ClassUnderTest {

    @XmlElement(required = true)
    protected String className;
    @XmlElement(required = true)
    protected String packageName;
    @XmlElement(required = true)
    protected ProcessingInfo processingInfo;
    @XmlElement(required = true)
    protected MutationRatio mutationRatio;
    @XmlElement(required = true)
    protected String baseClassFile;
    @XmlElement(required = true)
    protected String baseSourceFile;
    protected List<Mutant> mutant;
    protected List<String> executedTests;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the packageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageName() {
        return this.packageName;
    }

    /**
     * Sets the value of the packageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageName(String value) {
        this.packageName = value;
    }

    /**
     * Gets the value of the processingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingInfo }
     *     
     */
    public ProcessingInfo getProcessingInfo() {
        return this.processingInfo;
    }

    /**
     * Sets the value of the processingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingInfo }
     *     
     */
    public void setProcessingInfo(ProcessingInfo value) {
        this.processingInfo = value;
    }

    /**
     * Gets the value of the mutationRatio property.
     * 
     * @return
     *     possible object is
     *     {@link MutationRatio }
     *     
     */
    public MutationRatio getMutationRatio() {
        return this.mutationRatio;
    }

    /**
     * Sets the value of the mutationRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link MutationRatio }
     *     
     */
    public void setMutationRatio(MutationRatio value) {
        this.mutationRatio = value;
    }

    /**
     * Gets the value of the baseClassFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseClassFile() {
        return this.baseClassFile;
    }

    /**
     * Sets the value of the baseClassFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseClassFile(String value) {
        this.baseClassFile = value;
    }

    /**
     * Gets the value of the baseSourceFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseSourceFile() {
        return this.baseSourceFile;
    }

    /**
     * Sets the value of the baseSourceFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseSourceFile(String value) {
        this.baseSourceFile = value;
    }

    /**
     * Gets the value of the mutant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mutant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMutant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mutant }
     * 
     * 
     */
    public List<Mutant> getMutant() {
        if (this.mutant == null) {
            this.mutant = new ArrayList<Mutant>();
        }
        return this.mutant;
    }

    /**
     * Gets the value of the executedTests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executedTests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutedTests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExecutedTests() {
        if (this.executedTests == null) {
            this.executedTests = new ArrayList<String>();
        }
        return this.executedTests;
    }

}
