/**
 *
 *   Copyright Alexander Rau, Mike Groezinger, Retroduction.org - All rights reserved
 *
 *   This file is part of Carma. Carma is licensed under the OSL 3.0. The OSL 3.0 is
 *   available here: http://www.opensource.org/licenses/osl-3.0.php
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.05 at 10:03:07 PM CEST 
//


package com.retroduction.carma.xmlreport.om;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.retroduction.carma.xmlreport.om package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.retroduction.carma.xmlreport.om
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mutant }
     * 
     */
    public Mutant createMutant() {
        return new Mutant();
    }

    /**
     * Create an instance of {@link MutationRatio }
     * 
     */
    public MutationRatio createMutationRatio() {
        return new MutationRatio();
    }

    /**
     * Create an instance of {@link ClassUnderTest }
     * 
     */
    public ClassUnderTest createClassUnderTest() {
        return new ClassUnderTest();
    }

    /**
     * Create an instance of {@link ProcessingInfo }
     * 
     */
    public ProcessingInfo createProcessingInfo() {
        return new ProcessingInfo();
    }

    /**
     * Create an instance of {@link MutationRun }
     * 
     */
    public MutationRun createMutationRun() {
        return new MutationRun();
    }

}
